'use strict';

/**
 * API route handlers for the Homey AAOS Companion app.
 *
 * These functions are mapped to the routes declared in `.homeycompose/app.json`:
 *
 *  - `POST /auth/start`  → {@link startAuth}
 *  - `GET  /auth/poll`   → {@link pollAuth}
 *
 * Both routes are declared with `"public": true` so any device can call them without
 * a Homey Web API bearer token. This is intentional: the AAOS app does not yet have
 * a Homey token when it initiates the authentication flow.
 *
 * The only security mechanism protecting these endpoints is the `sessionId`, which is
 * a 64-character hex string generated with `SecureRandom` (256-bit entropy) by the
 * AAOS app. The token is delivered exactly once and is deleted immediately after retrieval.
 *
 * @module api
 */

/**
 * Handles `POST /auth/start`.
 *
 * Validates the incoming payload, delegates to `app.startAuthSession()` and returns
 * the authorization URL to be displayed as a QR code on the AAOS screen.
 *
 * @public
 * @param {object} args
 * @param {import('homey').Homey} args.homey - The Homey instance, providing access to `homey.app`.
 * @param {object} args.body - The parsed JSON request body.
 * @param {string} args.body.sessionId - A 64-char hex session identifier generated by the AAOS app.
 * @returns {Promise<{authUrl: string}>} The authorization URL to render as a QR code.
 * @throws Will propagate any error from `app.startAuthSession()` as an HTTP 500.
 * @example
 * // Request:
 * // POST https://{homeyId}.connect.athom.com/api/app/com.dimapp.aaos/auth/start
 * // Content-Type: application/json
 * // { "sessionId": "a1b2c3d4..." }
 * //
 * // Response:
 * // { "authUrl": "https://api.athom.com/oauth2/authorise?...&redirect_uri=https://callback.athom.com/..." }
 */
async function startAuth({ homey, body }) {
  const { sessionId } = body ?? {};

  if (!sessionId || typeof sessionId !== 'string' || sessionId.length < 16) {
    throw Object.assign(new Error('Missing or invalid sessionId.'), { statusCode: 400 });
  }

  return homey.app.startAuthSession(sessionId);
}

/**
 * Handles `GET /auth/poll`.
 *
 * Returns the current status of an auth session. When the user has authorized the app,
 * the token is included in the response and the session is immediately deleted from memory.
 *
 * @public
 * @param {object} args
 * @param {import('homey').Homey} args.homey - The Homey instance.
 * @param {object} args.query - The parsed query string parameters.
 * @param {string} args.query.session - The session identifier to poll.
 * @returns {{ status: 'pending'|'complete'|'expired', token?: object }} Current session state.
 * @example
 * // Request:
 * // GET https://{homeyId}.connect.athom.com/api/app/com.dimapp.aaos/auth/poll?session=a1b2c3...
 * //
 * // Response (pending):
 * // { "status": "pending" }
 * //
 * // Response (complete — one-time only):
 * // { "status": "complete", "token": { "access_token": "...", "refresh_token": "...", "expires_in": 3600 } }
 * //
 * // Response (expired or unknown):
 * // { "status": "expired" }
 */
function pollAuth({ homey, query }) {
  const sessionId = query?.session;

  if (!sessionId || typeof sessionId !== 'string') {
    throw Object.assign(new Error('Missing required query parameter: session.'), { statusCode: 400 });
  }

  return homey.app.pollAuthSession(sessionId);
}

/**
 * Handles `POST /auth/refresh`.
 *
 * Verifies the provided athom_refresh_token by querying Athom Cloud.
 * If valid, generates a new owner API token and returns it along with the new refresh token.
 *
 * @public
 * @param {object} args
 * @param {import('homey').Homey} args.homey - The Homey instance.
 * @param {object} args.body - The parsed JSON request body.
 * @returns {Promise<{session_token: string, athom_refresh_token: string}>} The new tokens.
 */
async function refreshAuth({ homey, body }) {
  const athomRefreshToken = body?.athom_refresh_token;

  if (!athomRefreshToken || typeof athomRefreshToken !== 'string') {
    throw Object.assign(new Error('Missing or invalid athom_refresh_token.'), { statusCode: 400 });
  }

  return homey.app.refreshAuthSession(athomRefreshToken);
}

async function getDashboards({ homey }) {
  console.log('[HomeyAaosCompanionApp] getDashboards request received');
  
  const selectedIds = homey.settings.get('home_devices_ids') || [];
  
  // If no devices are selected, return an empty list or a flag indicating fallback is needed.
  // The Android app will handle the fallback to Favorites.
  if (selectedIds.length === 0) {
    console.log('[HomeyAaosCompanionApp] No devices selected in settings, returning empty virtual dashboard');
    return {};
  }

  // Create a "Virtual Dashboard" that mirrors the structure HomeyRepository.kt expects
  // Key: dashboard ID, Value: Dashboard object
  const virtualDashboardId = 'virtual-aaos-home';
  const dashboard = {
    id: virtualDashboardId,
    columns: [
      {
        widgets: [
          {
            type: 'devices_custom',
            data: {
              deviceIds: selectedIds
            }
          }
        ]
      }
    ]
  };

  const response = {};
  response[virtualDashboardId] = dashboard;

  console.log(`[HomeyAaosCompanionApp] getDashboards successful: returning 1 virtual dashboard with ${selectedIds.length} devices.`);
  return response;
}

/**
 * Proxy for getting all lights and locks.
 * Used by the settings page.
 */
async function getDevices({ homey }) {
  console.log('[HomeyAaosCompanionApp] getDevices proxy called');
  
  const localUrl = await homey.api.getLocalUrl();
  const token = await homey.api.getOwnerApiToken();
  
  const response = await fetch(`${localUrl}/api/manager/devices/device`, {
    headers: { 'Authorization': `Bearer ${token}` }
  });
  
  if (!response.ok) {
    const errorBody = await response.text().catch(() => 'no body');
    console.error(`[HomeyAaosCompanionApp] getDevices proxy failed with status: ${response.status}. Details: ${errorBody}`);
    throw new Error(`Local API fetch failed with status: ${response.status}`);
  }
  
  const devices = await response.json();

  // Return only the fields needed by the settings UI to keep the payload small
  const filtered = {};
  for (const [id, device] of Object.entries(devices)) {
    if (device.class === 'light' || device.class === 'lock' || device.class === 'garagedoor') {
      filtered[id] = {
        id: device.id,
        name: device.name,
        class: device.class,
        zone: device.zone
      };
    }
  }
  return filtered;
}

/**
 * Proxy for getting all zones.
 * Used by the settings page.
 */
async function getZones({ homey }) {
  console.log('[HomeyAaosCompanionApp] getZones proxy called');
  
  const localUrl = await homey.api.getLocalUrl();
  const token = await homey.api.getOwnerApiToken();
  
  const response = await fetch(`${localUrl}/api/manager/zones/zone`, {
    headers: { 'Authorization': `Bearer ${token}` }
  });
  
  if (!response.ok) {
    const errorBody = await response.text().catch(() => 'no body');
    console.error(`[HomeyAaosCompanionApp] getZones proxy failed with status: ${response.status}. Details: ${errorBody}`);
    throw new Error(`Local API fetch failed with status: ${response.status}`);
  }
  
  return response.json();
}

module.exports = { startAuth, pollAuth, refreshAuth, getDashboards, getDevices, getZones };
